#!/bin/env python3

import unittest
from tagcounter.tagcounter import *

class Test(unittest.TestCase):
    """
    Here are placed all unittests for tagcounter app.
    """
    def test_counter(self):
        """
        Try to count HTML tags on the page
        """
        html = "<h1> My HTML </h1>"
        res, _useless = counter(html)
        self.assertEqual(res['h1'], 1)

    def test_GetResponse(self):
        resp = GetResponse('google.com')
        resp.get()
        self.assertIn(b'html', resp.body)

if __name__ == '__main__':
    unittest.main()
